# Generated by Django 5.1.3 on 2024-11-28 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='emi',
            old_name='installment_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='remaining_installments',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='repayment_interval',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='total_installments',
        ),
        migrations.AddField(
            model_name='emi',
            name='frequency',
            field=models.CharField(default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='emi',
            name='next_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to=settings.AUTH_USER_MODEL),
        ),
    ]
